name: Day 7 - Upload Artifact

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create Report
        run: |
          echo "GH-200 Practice Report" > report.txt
          echo "Date: $(date)" >> report.txt

      - name: Show Report
        run: cat report.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: practice-report
          path: report.txt
