name: Installed Software

on:
  workflow_dispatch:

jobs:
  software:
    runs-on: ubuntu-latest

    steps:
      - run: |
          git --version
          node --version
          python --version
